FROM python:3.8.6-slim-buster AS base

LABEL maintener="Dmitry Kisler"
LABEL email="admin@dkisler.com"
LABEL web="www.serverlessml.org"

WORKDIR /app

COPY . .
COPY main.py.gcp /main.py

RUN pip install pip==20.3 --upgrade \
    && pip install './serverlessml[gcp]' --no-cache-dir

RUN rm -rf /app \
    /tmp/* \
    /var/tmp/* \
    /usr/share/man \
    /usr/share/doc \
    /usr/share/doc-base

ENV PROJECT_ID "project"
ENV PORT 8000

EXPOSE ${PORT}

ENTRYPOINT [ "python", "/main.py" ]
