name: Build

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "Dockerfile*"
      - "main.py.*"
  pull_request:
    branches:
      - master
    types:
      - opened
  workflow_dispatch:

jobs:
  build-n-push:
    strategy:
      matrix:
        pyver: [3.7, 3.8]
        platform: [aws, gcp]
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build base image
        run: make build PY_VER=${{matrix.pyver}} PLATFORM=${{matrix.platform}}

      - name: Build demo image
        run: make build PY_VER=${{matrix.pyver}} PLATFORM=${{matrix.platform}} DEMO_SUFF=".demo"

      - name: Integration test
        run: |
          make run-${PLF}-local DEMO_SUFF=".demo" PLATFORM=${PLF}
          make test-e2e
          make rm PLATFORM=${PLF}
        env:
          PLF: ${{matrix.platform}}

      - name: Auth with docker hub
        run: echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_USER}" --password-stdin
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

      - name: Push images
        run: |
          make push PY_VER=${{matrix.pyver}} PLATFORM=${{matrix.platform}}
          make push-latest PY_VER=${{matrix.pyver}} PLATFORM=${{matrix.platform}}
